name: localmaterialnotes
description: Simple, local, material design notes
repository: https://github.com/maelchiotti/LocalMaterialNotes

version: 1.3.0+7
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  after_layout: ^1.2.0
  archive: ^3.6.0
  collection: ^1.18.0
  device_info_plus: ^10.1.0
  dynamic_color: ^1.7.0
  equatable: ^2.0.5
  fleather: ^1.14.5+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_settings_ui: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  fuzzywuzzy: ^1.1.6
  go_router: ^14.1.3
  intl: ^0.19.0
  is_first_run: ^1.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  locale_names: ^1.1.1
  material_symbols_icons: ^4.2744.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  quick_actions: ^1.0.7
  receive_sharing_intent: ^1.8.0
  restart_app: ^1.2.1
  riverpod_annotation: ^2.3.5
  sanitize_filename: ^1.0.5
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  shared_storage: ^0.8.1
  simple_icons: ^10.1.3
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.10
  custom_lint: ^0.5.11
  # TODO: replace when the monochrome feature is released on pub.dev
  # (cf. https://github.com/fluttercommunity/flutter_launcher_icons/issues/555)
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons
      ref: master
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  lint: ^2.3.0
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - lib/l10n/hardcoded_localizations.yaml
