name: localmaterialnotes
description: Simple, local, material design notes
repository: https://github.com/maelchiotti/LocalMaterialNotes

version: 1.12.0+25
publish_to: none

environment:
  sdk: ">=3.6.1 <4.0.0"
  flutter: 3.27.3

dependencies:
  after_layout: ^1.2.0
  archive: ^4.0.2
  back_button_interceptor: ^8.0.3
  collection: ^1.18.0
  dart_helper_utils: ^3.3.0
  device_info_plus: ^11.2.0
  dynamic_color: ^1.7.0
  encrypt: ^5.0.3
  equatable: ^2.0.7
  flag_secure: ^2.0.2
  fleather: ^1.20.0
  flex_color_picker: ^3.7.0
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_helper_utils: ^6.10.0
  flutter_localizations:
    sdk: flutter
  flutter_mimir: ^0.1.6
  flutter_native_splash: ^2.4.4
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_staggered_grid_view: ^0.7.0
  gap: ^3.0.1
  intl: ^0.19.0
  is_first_run: ^1.0.0
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  json_annotation: ^4.9.0
  locale_names: ^1.1.1
  logger: ^2.5.0
  material_symbols_icons: ^4.2801.1
  package_info_plus: ^8.1.2
  parchment: any
  parchment_delta: any
  path: ^1.9.0
  path_provider: ^2.1.5
  quick_actions: ^1.1.0
  receive_sharing_intent: # TODO: change when the fix is released
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
      ref: 2cea396843cd3ab1b5ec4334be4233864637874e
  restart_app: ^1.3.2
  riverpod_annotation: ^2.6.1
  saf_stream: ^0.11.0
  saf_util: ^0.6.1
  sanitize_filename: ^1.0.5
  settings_tiles: ^4.0.0
  share_plus: ^10.1.3
  shared_preferences: ^2.3.5
  simple_icons: ^10.1.3
  string_validator: ^1.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.14
  build_verify: ^3.1.0
  custom_lint: ^0.7.0
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  json_serializable: ^6.9.0
  patrol: ^3.13.2
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow/Barlow-Black.ttf
        - asset: assets/fonts/Barlow/Barlow-BlackItalic.ttf
        - asset: assets/fonts/Barlow/Barlow-Bold.ttf
        - asset: assets/fonts/Barlow/Barlow-BoldItalic.ttf
        - asset: assets/fonts/Barlow/Barlow-ExtraBold.ttf
        - asset: assets/fonts/Barlow/Barlow-ExtraBoldItalic.ttf
        - asset: assets/fonts/Barlow/Barlow-ExtraLight.ttf
        - asset: assets/fonts/Barlow/Barlow-ExtraLightItalic.ttf
        - asset: assets/fonts/Barlow/Barlow-Italic.ttf
        - asset: assets/fonts/Barlow/Barlow-Light.ttf
        - asset: assets/fonts/Barlow/Barlow-LightItalic.ttf
        - asset: assets/fonts/Barlow/Barlow-Medium.ttf
        - asset: assets/fonts/Barlow/Barlow-MediumItalic.ttf
        - asset: assets/fonts/Barlow/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow/Barlow-SemiBold.ttf
        - asset: assets/fonts/Barlow/Barlow-SemiBoldItalic.ttf
        - asset: assets/fonts/Barlow/Barlow-Thin.ttf
        - asset: assets/fonts/Barlow/Barlow-ThinItalic.ttf
    - family: Comic Sans MS
      fonts:
        - asset: assets/fonts/Comic_Sans_MS/ComicSansMS.ttf
    - family: Dancing Script
      fonts:
        - asset: assets/fonts/Dancing_Script/DancingScript-VariableFont_wght.ttf
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-VariableFont_wght.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Black.ttf
        - asset: assets/fonts/Merriweather/Merriweather-BlackItalic.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather/Merriweather-BoldItalic.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Italic.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Light.ttf
        - asset: assets/fonts/Merriweather/Merriweather-LightItalic.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Noto_Sans/NotoSans-VariableFont_wdth,wght.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-VariableFont_wdth,wght.ttf
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-VariableFont_wght.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Raleway/Raleway-VariableFont_wght.ttf
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Roboto_Mono/RobotoMono-VariableFont_wght.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf

patrol:
  android:
    package_name: com.maelchiotti.localmaterialnotes