name: localmaterialnotes
description: Simple, local, material design notes
repository: https://github.com/maelchiotti/LocalMaterialNotes
documentation: https://github.com/maelchiotti/LocalMaterialNotes/wiki

version: 1.1.1+4
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.2
  dynamic_color: ^1.6.9
  equatable: ^2.0.5
  fleather: ^1.14.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^2.4.10
  flutter_settings_ui: ^3.0.0
  go_router: ^13.1.0
  intl: ^0.18.1
  is_first_run: ^1.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  locale_names: ^1.1.1
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.2
  quick_actions: ^1.0.7
  receive_sharing_intent: ^1.6.7
  restart_app: ^1.2.1
  riverpod_annotation: ^2.3.4
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  shared_storage: ^0.8.1
  simple_icons: ^10.1.3
  url_launcher: ^6.2.4
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.5.11
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  lint: ^2.3.0
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
