name: localmaterialnotes
description: Simple, local, material design notes
repository: https://github.com/maelchiotti/LocalMaterialNotes

version: 1.6.0+13
publish_to: none

environment:
  sdk: ">=3.5.2 <4.0.0"
  flutter: 3.24.2

dependencies:
  after_layout: ^1.2.0
  archive: ^3.6.1
  back_button_interceptor: ^7.0.3
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.2
  dynamic_color: ^1.7.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  flag_secure: ^2.0.0
  fleather: ^1.19.0
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  flutter_settings_ui: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  fuzzywuzzy: ^1.2.0
  go_router: ^14.2.7
  intl: ^0.19.0
  is_first_run: ^1.0.0
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  json_annotation: ^4.9.0
  locale_names: ^1.1.1
  material_symbols_icons: ^4.2785.1
  package_info_plus: ^8.0.2
  parchment: any
  parchment_delta: any
  path: ^1.9.0
  path_provider: ^2.1.4
  quick_actions: ^1.0.7
  receive_sharing_intent: ^1.8.0
  restart_app: ^1.3.2
  riverpod_annotation: ^2.3.5
  sanitize_filename: ^1.0.5
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  # Contains custom fixes because this package is not maintained anymore
  shared_storage:
    git:
      url: https://github.com/maelchiotti/shared_storage
      ref: v0.8.1_fixed
  simple_icons: ^10.1.3
  url_launcher: ^6.3.0
  validators: ^3.0.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  custom_lint: ^0.6.7
  # TODO: replace when the monochrome feature is released on pub.dev
  # See https://github.com/fluttercommunity/flutter_launcher_icons/issues/555
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons
      ref: master
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  json_serializable: ^6.8.0
  lint: ^2.3.0
  patrol: ^3.10.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

patrol:
  android:
    package_name: com.maelchiotti.localmaterialnotes