name: localmaterialnotes
description: Simple, local, material design notes
repository: https://github.com/maelchiotti/LocalMaterialNotes

version: 1.7.1+15
publish_to: none

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: 3.24.3

dependencies:
  after_layout: ^1.2.0
  archive: ^3.6.1
  back_button_interceptor: ^7.0.3
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.0.0
  dynamic_color: ^1.7.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  file_selector: ^1.0.3
  flag_secure: ^2.0.0
  fleather: ^1.19.0
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  flutter_staggered_grid_view: ^0.7.0
  fuzzywuzzy: ^1.2.0
  go_router: ^14.3.0
  intl: ^0.19.0
  is_first_run: ^1.0.0
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  json_annotation: ^4.9.0
  locale_names: ^1.1.1
  material_symbols_icons: ^4.2788.0
  package_info_plus: ^8.0.3
  parchment: any
  parchment_delta: any
  path: ^1.9.0
  path_provider: ^2.1.4
  quick_actions: ^1.0.8
  receive_sharing_intent: ^1.8.0
  restart_app: ^1.3.2
  riverpod_annotation: ^2.3.5
  saf_stream: ^0.9.2
  saf_util: ^0.1.2
  sanitize_filename: ^1.0.5
  settings_tiles: ^2.0.0
  share_plus: ^10.0.3
  shared_preferences: ^2.3.2
  simple_icons: ^10.1.3
  url_launcher: ^6.3.1
  validators: ^3.0.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  custom_lint: ^0.6.7
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  json_serializable: ^6.8.0
  patrol: ^3.11.1
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

patrol:
  android:
    package_name: com.maelchiotti.localmaterialnotes